#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
# Input: s = "", t = "y"
# Output: "y"
# Constraints:
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
def find_the_difference(s: str, t: str) -> str:
    for i in s:
        t = t.replace(i, '', 1)
    return t


print(find_the_difference('abcd', 'abcde'))  # e
print(find_the_difference('a', 'aa'))  # a
print(find_the_difference('', 'y'))  # y
